name: pipedream-dispatch

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  # schedule:
    # - cron: '0 7/4 * * *'
  repository_dispatch:
    types: [BOT_SHEET_RUN]

jobs:
  build:
    name: Run botsheet.py
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: psirt_bot_enviro_1
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install --upgrade gspread
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        env:
          psirt_client_id: ${{ secrets.PSIRT_CLIENT_ID }}
          psirt_client_secret: ${{ secrets.PSIRT_CLIENT_SECRET }}
        run: |
          python botsheet.py