name: psirt-gsheet-dispatch

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  schedule:
    - cron: "0 */2 * * *"
  repository_dispatch:
    types: [BOT_SHEET_RUN]

jobs:
  build:
    name: Run botsheet.py
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    environment: psirt_gsheets
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
          check-latest: true
          cache: 'pip'
      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install --upgrade requests
          pip install --upgrade gspread
          pip install -r github-requirements.txt
          if [ -f github-requirements.txt ]; then pip install -r github-requirements.txt; fi
      - name: service_account.json
        id: service_account
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: "service_account.json"
          json: ${{ secrets.GSHEETS_SECRET}}
          # dir: 'src/'
      - name: Sleep for 2 seconds
        run: sleep 2s
        shell: bash
      - name: execute py script # run file
        env:
          psirt_client_id: ${{ secrets.PSIRT_CLIENT_ID }}
          psirt_client_secret: ${{ secrets.PSIRT_CLIENT_SECRET }}
        run: |
          python botsheet.py